# Kiwi Challenge

For each location find all possible trips.

In [1]:
import os
os.getcwd()

'C:\\Users\\chladek'

In [2]:
import pandas as pd
from datetime import datetime
import numpy as np

%reload_ext autoreload
%autoreload 2
from utils import *

In [321]:
# data frame
df = pd.read_csv('data1.csv',parse_dates=True)

In [322]:
# just instructional output
bags_0 = get_flights(df,0)
print('0 bags')
bags_0

C:\Users\chladek\AppData\Local\Continuum\anaconda3-64\envs\tf\lib\site-packages\ipykernel\__main__.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


0 bags


{'USM': [array([ 7, 14, 47], dtype=int64),
  array([ 0, 24], dtype=int64),
  array([ 1, 23], dtype=int64),
  array([ 3, 13, 42], dtype=int64),
  array([ 2, 25], dtype=int64),
  array([ 8, 19], dtype=int64),
  array([ 1, 14, 44], dtype=int64),
  array([ 3, 21], dtype=int64),
  array([ 9, 25], dtype=int64),
  array([ 4, 24], dtype=int64),
  array([10, 24], dtype=int64),
  array([ 5, 20, 37], dtype=int64),
  array([ 5, 19], dtype=int64),
  array([ 6, 22], dtype=int64),
  array([ 7, 26], dtype=int64),
  array([ 9, 19, 42], dtype=int64)],
 'HKT': [array([15, 70], dtype=int64),
  array([11,  7, 49], dtype=int64),
  array([20,  8, 37], dtype=int64),
  array([16,  5, 37], dtype=int64),
  array([20, 10, 42], dtype=int64),
  array([16, 18], dtype=int64),
  array([11, 23], dtype=int64),
  array([20,  6, 40], dtype=int64),
  array([17, 96], dtype=int64),
  array([12, 22], dtype=int64),
  array([18, 24], dtype=int64),
  array([13, 21], dtype=int64),
  array([19, 17], dtype=int64),
  array([14, 21],

In [323]:
# just instructional output
bags_1 = get_flights(df,1)
print('1 bag')
bags_1

C:\Users\chladek\AppData\Local\Continuum\anaconda3-64\envs\tf\lib\site-packages\ipykernel\__main__.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


1 bag


{'USM': [array([ 7, 14, 72], dtype=int64),
  array([ 0, 33], dtype=int64),
  array([ 1, 32], dtype=int64),
  array([ 3, 13, 64], dtype=int64),
  array([ 2, 39], dtype=int64),
  array([ 8, 27], dtype=int64),
  array([ 1, 14, 65], dtype=int64),
  array([ 3, 38], dtype=int64),
  array([ 9, 41], dtype=int64),
  array([ 4, 38], dtype=int64),
  array([10, 41], dtype=int64),
  array([ 5, 20, 62], dtype=int64),
  array([ 5, 32], dtype=int64),
  array([ 6, 40], dtype=int64),
  array([ 7, 39], dtype=int64),
  array([ 9, 19, 69], dtype=int64)],
 'HKT': [array([ 15, 109], dtype=int64),
  array([11,  7, 77], dtype=int64),
  array([20,  8, 57], dtype=int64),
  array([16,  5, 57], dtype=int64),
  array([20, 10, 71], dtype=int64),
  array([16, 25], dtype=int64),
  array([11, 38], dtype=int64),
  array([20,  6, 70], dtype=int64),
  array([ 17, 136], dtype=int64),
  array([12, 28], dtype=int64),
  array([18, 29], dtype=int64),
  array([13, 26], dtype=int64),
  array([19, 28], dtype=int64),
  array([14, 

In [324]:
# just instructional output
bags_2 = get_flights(df,2)
print('2 bags')
bags_2

C:\Users\chladek\AppData\Local\Continuum\anaconda3-64\envs\tf\lib\site-packages\ipykernel\__main__.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


2 bags


{'USM': [array([ 1, 41], dtype=int64),
  array([ 8, 35], dtype=int64),
  array([ 9, 57], dtype=int64),
  array([10, 58], dtype=int64),
  array([ 7, 52], dtype=int64)],
 'HKT': [array([18, 34], dtype=int64),
  array([13, 31], dtype=int64),
  array([16, 32], dtype=int64)],
 'BWN': [array([ 31, 118], dtype=int64),
  array([ 26, 100], dtype=int64),
  array([27, 99], dtype=int64),
  array([30, 85], dtype=int64)],
 'DPS': [array([ 36, 160], dtype=int64),
  array([ 38, 167], dtype=int64),
  array([33, 93], dtype=int64),
  array([ 33,  31, 211], dtype=int64)]}

In [ ]:
# example how to access trips

# price
bags_0['USM'][0][-1]

# trip
bags_0['USM'][0]